providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npx prisma migrate deploy && npm run start"

[variables]
NEXT_TELEMETRY_DISABLED = "1"
NODE_ENV = "production"
